__forceinline void DebugSelf()
{
	HANDLE hProcess = NULL;
	DEBUG_EVENT de;
	PROCESS_INFORMATION pi;
	STARTUPINFO si;
	ZeroMemory(&pi, sizeof(PROCESS_INFORMATION));
	ZeroMemory(&si, sizeof(STARTUPINFO));
	ZeroMemory(&de, sizeof(DEBUG_EVENT));

	GetStartupInfo(&si);

	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);
	CreateProcess(NULL, GetCommandLine(), NULL, NULL, FALSE, CREATE_SECURE_PROCESS, NULL, NULL, &si, &pi);

	ContinueDebugEvent(pi.dwProcessId, pi.dwThreadId, DBG_TERMINATE_PROCESS);

	WaitForDebugEvent(&de, INFINITE);
}